export const FETCH_DOCUMENT_INFOBLOCKS = 'FETCH_DOCUMENT_INFOBLOCKS';
export const FETCH_EDITOR_INFOBLOCKS = 'FETCH_EDITOR_INFOBLOCKS';
export const INCLUDE_INFOBLOCKS = 'INCLUDE_INFOBLOCKS';
export const EXCLUDE_INFOBLOCKS = 'EXCLUDE_INFOBLOCKS';
export const FETCH_TERMS_WITH_BLOCKS = 'FETCH_TERMS_WITH_BLOCKS';
export const FETCH_INFOBLOCKS_TYPES = 'FETCH_INFOBLOCKS_TYPES';

export const SYNC_INFOBLOCKS = 'SYNC_INFOBLOCKS';

export const SELECT_INFOBLOCK = 'SELECT_INFOBLOCK';
export const ADD_INFOBLOCK = 'ADD_INFOBLOCK';
export const INSERT_INFOBLOCK = 'INSERT_INFOBLOCK';
export const REMOVE_INFOBLOCK = 'REMOVE_INFOBLOCK';
export const DUPLICATE_INFOBLOCK = 'DUPLICATE_INFOBLOCK';
export const SHOW_HIDE_INFOBLOCK = 'SHOW_HIDE_INFOBLOCK';
export const OPEN_EDIT_INFOBLOCK = 'OPEN_EDIT_INFOBLOCK';
export const SAVE_INFOBLOCK = 'SAVE_INFOBLOCK';
export const LOCK_UNLOCK_INFOBLOCK = 'LOCK_UNLOCK_INFOBLOCK';
export const OPEN_CLOSE_INFOBLOCK = 'OPEN_CLOSE_INFOBLOCK';
export const SELECT_ALL_INFOBLOCKS = 'SELECT_ALL_INFOBLOCKS';
export const BULK_DELETE_INFOBLOCKS = 'BULK_DELETE_INFOBLOCKS';
export const BULK_LOCK_INFOBLOCKS = 'BULK_LOCK_INFOBLOCKS';